package com.enumm.enums;

public enum ErrorCode {
    EMAIL_IN_USE,
    VERIFICATION_RESENT,
    VALIDATION_ERROR,
    EMAIL_NOT_VERIFIED,
    INVALID_CREDENTIALS,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_ALREADY_USED,
    RATE_LIMITED,
    NOT_AUTHENTICATED,
    INTERNAL_ERROR
}